version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./htdocs:/var/www/html:z
      - ./compose.conf/default.conf:/etc/nginx/conf.d/default.conf:z

  php-fpm:
    build: .
    volumes:
      - ./htdocs:/var/www/html:z
